### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by bsvural** [jacobbednarz/atom-github-2014-syntax#1]
In index.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by jacobbednarz** [comment]
Thanks! I've looked into fixing this and unfortunately it's not a simple find and replace to resolve this so I'll have a look at the best approach for fixing this one and maintaining backwards compatibility.

**Comment by ahmadseleem** [comment]
Curious to know why is it that hard ?

**Comment by jacobbednarz** [comment]
My tests were very hit and miss with backwards compatibility and in most cases broke it so terribly that either the editor pane wasn't available or the selectors didn't match appropriately. 

Happy to accept a pull request to resolve this if you would like to have a crack at it!

**Comment by ahmadseleem** [comment]
Have you looked at some other themes like the similar: github-2014 ?

I'm just new to Atom, I usually use Emacs with Evil-mode. I need to find sometime to look on how Atom packages work.

**Comment by ahmadseleem** [comment]
I couldn't give up on some of the colors of this light theme.
So, I just hacked this:
https://github.com/ahmadseleem/mac_github

A very quick hack, but no deprecation problem. Hopefully I can work more on that.

**Comment by ahmadseleem** [comment]
I just changed the name:
https://github.com/ahmadseleem/mac-github-syntax
